import { ThemeProvider } from "./components/theme-provider";

import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "nobr | Home",
  description: "Generated by create next app",
};

import { Inter } from "next/font/google";

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});
 

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className} suppressHydrationWarning>
      <head>
        <link
          rel="shortcut icon"
          href="./light-nobr-logo.svg"
          type="image/x-icon"
          className="dark:invert dark:filter"
        />
      </head>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <body className="min-h-screen antialiased">
          <NavBar />
          {children}
          <Footer />
        </body>
      </ThemeProvider>
    </html>
  );
}
