import { ThemeProvider } from "./components/theme-provider";
import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "nobr | Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          rel="shortcut icon"
          href="./light-nobr-logo.svg"
          type="image/x-icon"
          className="dark:invert dark:filter"
        />
      </head>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <body className="min-h-screen font-sans antialiased">
          <NavBar />
          {children}
          <Footer />
        </body>
      </ThemeProvider>
    </html>
  );
}
